basePath: /api
consumes:
- application/json
definitions:
  Login:
    properties:
      password:
        description: The password to login
        example: mySecretPassword
        type: string
        x-go-name: Password
      username:
        description: The username to login
        example: myUserName
        type: string
        x-go-name: Username
    required:
    - username
    - password
    type: object
    x-go-package: github.com/Davidmnj91/myrents/pkg/auth/login
  Profile:
    properties:
      birth_date:
        description: The BirthDate of the user
        example: "2000-12-12"
        type: string
        x-go-name: BirthDate
      email:
        description: The Email of the user
        example: myemail@me.com
        type: string
        x-go-name: Email
      id_number:
        description: The IDNumber of the user
        example: 01234567-N
        type: string
        x-go-name: IDNumber
      name:
        description: The Name of the user
        example: David
        type: string
        x-go-name: Name
      phone:
        description: The Phone of the user
        example: "666000222"
        type: string
        x-go-name: Phone
      surname:
        description: The Surname of the user
        example: Sanchez
        type: string
        x-go-name: Surname
      username:
        description: The name of the user in the app
        example: myUserName
        type: string
        x-go-name: Username
    type: object
    x-go-package: github.com/Davidmnj91/myrents/pkg/user/user_profile
  RegisterRealState:
    properties:
      country:
        description: The country of the real state address
        example: Spain
        type: string
        x-go-name: Country
      door:
        description: The Door of the real state address
        example: 2Iz
        type: string
        x-go-name: Door
      gateway:
        description: The gateway of the real state address
        example: 19Bis
        type: string
        x-go-name: Gateway
      land_reference:
        description: The owner of the real state uuid
        example: 1234-5678-9012-3456
        type: string
        x-go-name: LandReference
      landlord:
        description: The owner's uuid of the real state
        example: 1234-5678-9012-3456
        type: string
        x-go-name: Landlord
      province:
        description: The province of the real state address
        example: Madrid
        type: string
        x-go-name: Province
      sq_meters:
        description: The Size of the real state
        example: "120"
        type: string
        x-go-name: SqMeters
      street:
        description: The street of the real state address
        example: C/ False
        type: string
        x-go-name: Street
      zip_code:
        description: The zip code of the real state address
        example: "057890"
        type: string
        x-go-name: ZipCode
    required:
      - land_reference
      - street
      - zip_code
      - province
      - country
      - gateway
      - landlord
    type: object
    x-go-name: Register
    x-go-package: github.com/Davidmnj91/myrents/pkg/real_state/real_state_register
  RegisterUser:
    properties:
      birth_date:
        description: The BirthDate of the user
        example: "2000-12-12"
        type: string
        x-go-name: BirthDate
      email:
        description: The Email of the user
        example: myemail@me.com
        type: string
        x-go-name: Email
      id_number:
        description: The IDNumber of the user
        example: 01234567-N
        type: string
        x-go-name: IDNumber
      name:
        description: The Name of the user
        example: David
        type: string
        x-go-name: Name
      password:
        description: The Password of the user
        example: mySecretPassword
        type: string
        x-go-name: Password
      phone:
        description: The Phone of the user
        example: "666000222"
        type: string
        x-go-name: Phone
      surname:
        description: The Surname of the user
        example: Sanchez
        type: string
        x-go-name: Surname
      username:
        description: The name of the user in the app
        example: myUserName
        type: string
        x-go-name: Username
    required:
      - username
      - password
      - name
      - surname
      - id_number
      - email
      - phone
      - birth_date
    type: object
    x-go-name: Register
    x-go-package: github.com/Davidmnj91/myrents/pkg/user/user_register
host: localhost:5000
info:
  description: Documentation of our MyRents API.
  title: MyRents
  version: 1.0.0
paths:
  /login:
    post:
      operationId: login-user
      parameters:
      - description: Body to log in a user
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        "200":
          $ref: '#/responses/logged-user'
        "500":
          description: Internal server error
      summary: Logs in a user account into the system.
      tags:
      - auth
  /logout:
    delete:
      operationId: logout
      responses:
        "200":
          description: Successful logout
        "500":
          description: Internal server error
      security:
      - loggedIn:
        - '[]'
      summary: Logs out a user account from the system.
      tags:
      - auth
  /profile:
    get:
      operationId: profile-user
      responses:
        "200":
          description: Successful retrieval
          schema:
            $ref: '#/definitions/Profile'
        "500":
          description: Internal server error
      security:
        - loggedIn:
            - '[]'
      summary: Returns the authenticated user's profile.
      tags:
        - user
  /real-state/register:
    post:
      operationId: register-real-state
      parameters:
        - description: Body to register a new real state
          in: body
          name: Body
          required: true
          schema:
            $ref: '#/definitions/RegisterRealState'
      responses:
        "200":
          description: Successful registration
        "500":
          description: Internal server error
      security:
        - loggedIn:
            - '[]'
      summary: Creates a new real state for the owner in the system.
      tags:
        - realState
  /register:
    post:
      operationId: register-user
      parameters:
        - description: Body to register a user
          in: body
          name: Body
          required: true
          schema:
            $ref: '#/definitions/RegisterUser'
      responses:
        "200":
          description: Successful registration
        "500":
          description: Internal server error
      summary: Creates a new user in the system.
      tags:
      - user
  /removeAccount:
    delete:
      operationId: remove-account
      responses:
        "200":
          description: Successful delete
        "500":
          description: Internal server error
      security:
      - loggedIn:
        - '[]'
      summary: Deletes an existing account on the system.
      tags:
      - user
produces:
- application/json
responses:
  logged-user:
    description: Successfully logged-in user
    headers:
      Authorization:
        description: The authenticated user bearer JWT token Bearer base64EncodedJwtToken
        type: string
schemes:
- http
security:
- loggedIn:
  - '[]'
securityDefinitions:
  loggedIn:
    description: Bearer token of the logged-in user
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
